apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api
  namespace: dev
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`api.local`)
      services:
        - name: api
          port: 80
  tls:
    certResolver: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-redirect-to-https
  namespace: dev
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`api.local`)
      services:
        - name: api
          port: 80
      middlewares:
        - name: https-redirect
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: dev
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: "443"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: wil42/playground:v2
          ports:
            - containerPort: 8888
              name: api-port
          resources:
            requests:
              memory: "150Mi"
              cpu: "200m"
            limits:
              memory: "300Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: dev
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: api-port
